### ISSUE TITLE
User Tracking

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#559]
We need to be able to track users multiple different ways.

- [ ] Track users by hours connected to chat.
- [ ] Build out a points system. System should allow at least two (preferrably more) points types.
- [ ] Points and hours should be viewable in user list in the GUI.
